## YAML Template.
## Author: Brighter Agyemang

server:
  type: simple
  applicationContextPath: /ma
  adminContextPath: /admin-ma
  connector:
    type: http
    port: 8010
logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: logs/appLog.log
      archivedLogFilenamePattern: logs/archive/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC+8
      maxFileSize: 10MB
---
