/* 
 * Copyright (c) Yulin Zhang
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package org.mars.m2m.demo.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import org.mars.m2m.demo.config.OpStaticInitConfig;
import org.mars.m2m.demo.world.KnowledgeInterface;

/**
 *
 * @author Yulin_Zhang
 */
public class RightControlPanel extends javax.swing.JPanel implements TreeSelectionListener,MouseListener,ActionListener {

    private static KnowledgeInterface kb;
    private JPopupMenu popMenu;
    /**
     * Creates new form RightControlPanel
     */
    public RightControlPanel() {
        initComponents();
        RightControlPanel.jTree1.addMouseListener(this);
        RightControlPanel.jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        RightControlPanel.jTree1.addTreeSelectionListener(this);
        
        popMenu=new JPopupMenu();
        JMenuItem dellItem=new JMenuItem("Delete");
        popMenu.add(dellItem);
        dellItem.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        controlPanel1 = new org.mars.m2m.demo.ui.ControlPanel();

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        this.controlPanel = new ControlPanel();
        jSplitPane1.setRightComponent(this.controlPanel);

        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setRightComponent(jScrollPane1);
        jSplitPane1.setLeftComponent(controlPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void setWorldKnowledge(KnowledgeInterface kb)
    {
        RightControlPanel.kb=kb;
        RightControlPanel.jTree1.setModel(kb);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.mars.m2m.demo.ui.ControlPanel controlPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSplitPane jSplitPane1;
    private ControlPanel controlPanel;
    public static javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(TreeSelectionEvent e) 
    {
        Object select_obj = RightControlPanel.jTree1.getLastSelectedPathComponent();
        if (select_obj!=null&&kb.isLeaf(select_obj)) {
            String node_name = select_obj.toString();
            int index = -1;
            if (node_name.contains(OpStaticInitConfig.OBSTACLE_NAME)) {
                int index_name_prefix = node_name.indexOf(OpStaticInitConfig.OBSTACLE_NAME) + OpStaticInitConfig.OBSTACLE_NAME.length();
                index = Integer.parseInt(node_name.substring(index_name_prefix));
                AnimationPanel.highlight_obstacle_index = index;
            } else if (node_name.contains(OpStaticInitConfig.THREAT_NAME)) {
                int index_name_prefix = node_name.indexOf(OpStaticInitConfig.THREAT_NAME) + OpStaticInitConfig.THREAT_NAME.length();
                index = Integer.parseInt(node_name.substring(index_name_prefix));
                AnimationPanel.highlight_threat_index = index;
            } else if (node_name.contains(OpStaticInitConfig.CONFLICT_NAME)) {
                int index_name_prefix = node_name.indexOf(OpStaticInitConfig.CONFLICT_NAME) + OpStaticInitConfig.CONFLICT_NAME.length();
                index = Integer.parseInt(node_name.substring(index_name_prefix));
                AnimationPanel.highlight_uav_index = index;
            }
        } else if(select_obj!=null){
            AnimationPanel.highlight_obstacle_index =-1;
            AnimationPanel.highlight_threat_index =-1;
            AnimationPanel.highlight_uav_index = -1;
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
        TreePath path=RightControlPanel.jTree1.getPathForLocation(e.getX(), e.getY());
        if(path==null)
            return;
        RightControlPanel.jTree1.setSelectionPath(path);
        boolean is_leaf_selected= RightControlPanel.kb.isLeaf(path.getLastPathComponent());
        if(e.getButton()==MouseEvent.BUTTON3 && is_leaf_selected)
        {
            popMenu.show(jTree1, e.getX(), e.getY());
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        TreePath path=RightControlPanel.jTree1.getSelectionPath();
        RightControlPanel.kb.deleteComponent(path,RightControlPanel.jTree1.getLastSelectedPathComponent());
        RightControlPanel.jTree1.setModel(RightControlPanel.kb);
        RightControlPanel.jTree1.removeSelectionPath(path);
    }
}
