/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mars.m2m.demo.ui;

/**
 *
 * @author AG BRIGHTER
 */
public class Sidebar extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Sidebar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane_sidebar = new javax.swing.JSplitPane();
        rightControlPanel1 = new org.mars.m2m.demo.ui.RightControlPanel();
        logWindow1 = new org.mars.m2m.demo.ui.LogWindow();

        jSplitPane_sidebar.setDividerLocation(300);
        jSplitPane_sidebar.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane_sidebar.setLeftComponent(rightControlPanel1);
        jSplitPane_sidebar.setRightComponent(logWindow1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane_sidebar;
    private org.mars.m2m.demo.ui.LogWindow logWindow1;
    private org.mars.m2m.demo.ui.RightControlPanel rightControlPanel1;
    // End of variables declaration//GEN-END:variables
}
