## YAML Template.
## Author: Brighter Agyemang

server:
  type: simple
  applicationContextPath: /cc
  adminContextPath: /admin-cc
  connector:
    type: http
    port: 8170
logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: logs/appLog.log
      archivedLogFilenamePattern: logs/archive/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC+8
      maxFileSize: 10MB
      
controlCenter_address: http://127.0.0.1:8170
controlCenter_notificationURL: http://127.0.0.1:8170/cc/notification/
mgmntServerURL: http://127.0.0.1:8089/ms/clients/
mgmntAdapterURL: http://127.0.0.1:8070/ma/mgmtAdapter/
