/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.mars.m2m.demo.controlcenter.ui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author AG BRIGHTER
 */
public class ResourcePanel extends javax.swing.JPanel {

    /**
     * Creates new form ResourcePanel
     */
    public ResourcePanel() {
        initComponents();
        setProperties();
    }

    private void setProperties() {
        try 
        {
            this.readBtn.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/icons/play.png"))));
            this.updateBtn.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/icons/refresh.png"))));
            this.observeBtn.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/icons/eye-open.png"))));
            this.cancelObservationBtn.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/icons/eye-close.png"))));
        } catch (IOException ex) {
            Logger.getLogger(ResourcePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resourceID = new javax.swing.JLabel();
        resourceName = new javax.swing.JLabel();
        pnlOperationalbtns = new javax.swing.JPanel();
        readBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        observeBtn = new javax.swing.JButton();
        cancelObservationBtn = new javax.swing.JButton();
        resourceValue = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 33));
        setMinimumSize(new java.awt.Dimension(400, 33));
        setPreferredSize(new java.awt.Dimension(670, 33));

        resourceID.setText("RID");

        resourceName.setText("Resource name");

        readBtn.setText("Read");
        pnlOperationalbtns.add(readBtn);

        updateBtn.setText("Update");
        pnlOperationalbtns.add(updateBtn);

        observeBtn.setText("Observe");
        pnlOperationalbtns.add(observeBtn);

        cancelObservationBtn.setText("Cancel");
        pnlOperationalbtns.add(cancelObservationBtn);

        resourceValue.setText("Resource value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resourceID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resourceName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlOperationalbtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resourceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(resourceID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(resourceName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlOperationalbtns, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(resourceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelObservationBtn;
    private javax.swing.JButton observeBtn;
    private javax.swing.JPanel pnlOperationalbtns;
    private javax.swing.JButton readBtn;
    private javax.swing.JLabel resourceID;
    private javax.swing.JLabel resourceName;
    private javax.swing.JLabel resourceValue;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
