//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 11:15:39 AM CST 
//


package org.mars.m2m.dmcore.onem2m.xsdBundle;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announceableResource"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nodeID" type="{http://www.onem2m.org/xml/protocols}nodeID"/&gt;
 *         &lt;element name="hostedCSELink" type="{http://www.onem2m.org/xml/protocols}ID" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/&gt;
 *           &lt;choice maxOccurs="unbounded"&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}memory"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}battery"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}areaNwkInfo"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}areaNwkDeviceInfo"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}firmware"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}software"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}deviceInfo"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}deviceCapability"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}reboot"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}eventLog"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}cmdhPolicy"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}activeCmdhPolicy"/&gt;
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeID",
    "hostedCSELink",
    "childResource",
    "memoryOrBatteryOrAreaNwkInfo"
})
@XmlRootElement(name = "node")
public class Node
    extends AnnounceableResource
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nodeID;
    @XmlSchemaType(name = "anyURI")
    protected String hostedCSELink;
    protected List<ChildResourceRef> childResource;
    @XmlElements({
        @XmlElement(name = "memory", namespace = "http://www.onem2m.org/xml/protocols", type = Memory.class),
        @XmlElement(name = "battery", namespace = "http://www.onem2m.org/xml/protocols", type = Battery.class),
        @XmlElement(name = "areaNwkInfo", namespace = "http://www.onem2m.org/xml/protocols", type = AreaNwkInfo.class),
        @XmlElement(name = "areaNwkDeviceInfo", namespace = "http://www.onem2m.org/xml/protocols", type = AreaNwkDeviceInfo.class),
        @XmlElement(name = "firmware", namespace = "http://www.onem2m.org/xml/protocols", type = Firmware.class),
        @XmlElement(name = "software", namespace = "http://www.onem2m.org/xml/protocols", type = Software.class),
        @XmlElement(name = "deviceInfo", namespace = "http://www.onem2m.org/xml/protocols", type = DeviceInfo.class),
        @XmlElement(name = "deviceCapability", namespace = "http://www.onem2m.org/xml/protocols", type = DeviceCapability.class),
        @XmlElement(name = "reboot", namespace = "http://www.onem2m.org/xml/protocols", type = Reboot.class),
        @XmlElement(name = "eventLog", namespace = "http://www.onem2m.org/xml/protocols", type = EventLog.class),
        @XmlElement(name = "cmdhPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = CmdhPolicy.class),
        @XmlElement(name = "activeCmdhPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = ActiveCmdhPolicy.class),
        @XmlElement(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class)
    })
    protected List<RegularResource> memoryOrBatteryOrAreaNwkInfo;

    /**
     * Gets the value of the nodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeID() {
        return nodeID;
    }

    /**
     * Sets the value of the nodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeID(String value) {
        this.nodeID = value;
    }

    /**
     * Gets the value of the hostedCSELink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostedCSELink() {
        return hostedCSELink;
    }

    /**
     * Sets the value of the hostedCSELink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostedCSELink(String value) {
        this.hostedCSELink = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the memoryOrBatteryOrAreaNwkInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memoryOrBatteryOrAreaNwkInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemoryOrBatteryOrAreaNwkInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Memory }
     * {@link Battery }
     * {@link AreaNwkInfo }
     * {@link AreaNwkDeviceInfo }
     * {@link Firmware }
     * {@link Software }
     * {@link DeviceInfo }
     * {@link DeviceCapability }
     * {@link Reboot }
     * {@link EventLog }
     * {@link CmdhPolicy }
     * {@link ActiveCmdhPolicy }
     * {@link Subscription }
     * 
     * 
     */
    public List<RegularResource> getMemoryOrBatteryOrAreaNwkInfo() {
        if (memoryOrBatteryOrAreaNwkInfo == null) {
            memoryOrBatteryOrAreaNwkInfo = new ArrayList<RegularResource>();
        }
        return this.memoryOrBatteryOrAreaNwkInfo;
    }

}
