//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 11:15:39 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.onem2m.org/xml/protocols")
package org.mars.m2m.dmcore.onem2m.xsdBundle;
